### ISSUE TITLE
a typo

### ISSUE THREAD

**Issue by olned** [TekMonksGitHub/xforge#2]
Probably [here](https://github.com/TekMonksGitHub/xforge/blob/master/extensions/os_cmd.js#L13)  and [here](https://github.com/TekMonksGitHub/xforge/blob/master/extensions/ssh_cmd.js#L24) is the same typo, in the word **`exhaused`** lacks **` t`**

**Comment by TekMonksGitHub** [comment]
Agree.. it's a spelling mistake that should be fixed, especially as it is in a user message.
